version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: remix-mysql
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: remix-db
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
